// Generated by scripts/extract-frames.mjs. Do not edit by hand.
export const FRAME_COUNT = 313;
export const frameSrc = (i: number) =>
  `/intro-frames/frame_${String(i + 1).padStart(4, "0")}.webp`;
