// Extracts the hero video into a WebP frame sequence for the scroll-scrubbed
// intro, and records the frame count where the component can import it.
// Re-run after replacing public/hero.mp4:  node scripts/extract-frames.mjs
import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import ffmpeg from "ffmpeg-static";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public", "intro-frames");
const video = join(root, "public", "hero.mp4");

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

// 24 fps so scroll-wheel steps land between finer frames; scale to max 1080p
// on the long edge. The eq/vignette/noise chain is a documentary grade that
// knocks the clean "AI render" sheen off generated footage: muted colors,
// film grain (fresh per frame via allf=t+u), and a subtle corner falloff.
const args = [
  "-i", video,
  "-vf",
  "fps=24,scale='if(gt(iw,ih),min(iw,1920),-2)':'if(gt(iw,ih),-2,min(ih,1080))'," +
    "eq=saturation=0.72:contrast=1.07:brightness=-0.015," +
    "vignette=angle=PI/5," +
    "noise=alls=7:allf=t+u",
  "-c:v", "libwebp",
  "-quality", "72",
  join(outDir, "frame_%04d.webp"),
];

try {
  execFileSync(ffmpeg, args, { stdio: "inherit" });
} catch {
  // Static builds occasionally lack libwebp — fall back to JPEG.
  console.warn("WebP encode failed, falling back to JPEG.");
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  execFileSync(
    ffmpeg,
    ["-i", video, "-vf", args[3], "-q:v", "4", join(outDir, "frame_%04d.jpg")],
    { stdio: "inherit" }
  );
}

const frames = readdirSync(outDir).filter((f) => f.startsWith("frame_"));
const ext = frames[0].slice(frames[0].lastIndexOf(".") + 1);
writeFileSync(
  join(root, "app", "introFrames.ts"),
  `// Generated by scripts/extract-frames.mjs — do not edit by hand.\n` +
    `export const FRAME_COUNT = ${frames.length};\n` +
    `export const frameSrc = (i: number) =>\n` +
    `  \`/intro-frames/frame_\${String(i + 1).padStart(4, "0")}.${ext}\`;\n`
);
console.log(`Extracted ${frames.length} ${ext} frames to public/intro-frames`);
